display_name: ScriptKit
package_name: scriptkit
maintainer:
  name: ScriptKit maintainers
  email: noreply@example.com
essential: false
icon: assets/ScriptKit_logo.png
generic_name: Homework formatter
keywords:
  - homework
  - formatter
  - script
categories:
  - Utility
startup_notify: true